In [1]:
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape

(3,)

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
b.shape

(2, 4)

In [10]:
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
d= np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]],[[23,24,25,26], [27,28,29,30],[31,32,33,34]]])
print(d)

[[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]

 [[23 24 25 26]
  [27 28 29 30]
  [31 32 33 34]]]


In [16]:
d.shape

(2, 3, 4)

In [17]:
e= np.random.randint(1,10, size = (2,3,4,5))
print(e)

[[[[3 8 4 4 9]
   [2 5 6 5 9]
   [7 4 5 2 2]
   [9 5 1 4 7]]

  [[8 7 5 6 5]
   [8 6 6 2 4]
   [8 9 7 4 5]
   [4 2 7 6 8]]

  [[3 7 4 7 2]
   [5 5 9 9 4]
   [5 2 7 3 4]
   [8 5 2 4 9]]]


 [[[4 1 3 5 2]
   [9 9 3 7 2]
   [6 2 9 6 9]
   [7 8 8 2 4]]

  [[5 3 1 8 7]
   [3 9 1 1 3]
   [1 2 1 5 6]
   [3 3 4 6 8]]

  [[4 7 3 4 3]
   [1 2 5 5 3]
   [4 5 8 2 7]
   [3 6 5 1 7]]]]


In [18]:
l =[1,2,3]
print(l)
f= np.array([1,2,3])
print(f)

[1, 2, 3]
[1 2 3]


In [19]:
l*2

[1, 2, 3, 1, 2, 3]

In [20]:
f*2

array([2, 4, 6])

In [21]:
f.ndim

1

In [22]:
e.ndim

4

In [24]:
e.size

120

In [25]:
e.dtype

dtype('int32')

In [26]:
a.dtype

dtype('int64')

In [27]:
g = a.astype(float)
print(g)

[1. 2. 3.]


In [29]:
#memory - list
import sys
h = sys.getsizeof(l)
print(h)

88


In [31]:
i = h*len(l)
print(i)

264


In [32]:
#memory -array
j = np.array([4,5,6])
print(j)

[4 5 6]


In [33]:
k = j.itemsize
print(k)

8


In [34]:
m = k* j.size
print(m)

24


In [50]:
#performace
import time
# list
size = 10000
list1 = range(size)
print(list1)
list2 = range(size)
before_time = time.time()
print(before_time)
resultant_list = [(a*b) for a, b in zip(list1,list2)]
print(time.time() - before_time)

range(0, 10000)
1782531403.4200206
0.0032486915588378906


In [49]:
#numpy
n1 = np.arange(size)
print(n)
n2 = np.arange(size)
before_time = time.time()
print(before_time)
resultant_array = n1*n2
print(time.time() - before_time)

[   0    1    2 ... 9997 9998 9999]
1782531400.9874618
0.004709005355834961


In [53]:
o = np.zeros((3,3))
print(o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
o = np.zeros((3,3), dtype = int)
print(o)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [56]:
p = np.ones((4,4), dtype = int)
print(p)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [57]:
q = np.arange(6)
print(q)

[0 1 2 3 4 5]


In [58]:
r = np.arange(10,20,2)
print(r)

[10 12 14 16 18]


In [60]:
s = np.random.random(5) # 2 random because 1st random is amodule and 2 nd random is a function form it
print(s)

[0.31203754 0.35179739 0.43852085 0.21077576 0.43525065]


In [70]:
T = np.full((3,3), 30)
print(T)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [71]:
t = [1,2,3]
print(t)
t2=(1,2,3)
print(t2)

[1, 2, 3]
(1, 2, 3)


In [72]:
t3 = np.array(t)
print(t3)

[1 2 3]


In [73]:
t4 = np.array(t2)
print(t4)

[1 2 3]


In [77]:
u = np.arange(6)
u[2:5]

array([2, 3, 4])

In [78]:
u2 = np.arange(16)
u2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [80]:
u2[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [81]:
u3 = np.random.random(10)
u3

array([0.31057062, 0.61819083, 0.84789933, 0.14915997, 0.17208534,
       0.47351824, 0.33271853, 0.54849173, 0.24585552, 0.08848482])

In [82]:
u3[::2]

array([0.31057062, 0.84789933, 0.17208534, 0.33271853, 0.24585552])

In [83]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [84]:
print(b[1,3]) # single elemet when putting comma and no isto(:)

8


In [89]:
b1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b1[0:2]) # only row

[[1 2 3 4]
 [5 6 7 8]]


In [93]:
b2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b2[0:2,:3]) # slicing rows and colums because thsre is comma and isto

[[1 2 3]
 [5 6 7]]


In [96]:
d= np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]],[[23,24,25,26], [27,28,29,30],[31,32,33,34]],[[35,36,37,38],[1,2,3,4],[5,6,7,8]]])
print(d[0:2])

[[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]

 [[23 24 25 26]
  [27 28 29 30]
  [31 32 33 34]]]


In [97]:
d1= np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]],[[23,24,25,26], [27,28,29,30],[31,32,33,34]],[[35,36,37,38],[1,2,3,4],[5,6,7,8]]])
print(d1[0:2,:2])

[[[11 12 13 14]
  [15 16 17 18]]

 [[23 24 25 26]
  [27 28 29 30]]]


In [99]:
d2= np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]],[[23,24,25,26], [27,28,29,30],[31,32,33,34]],[[35,36,37,38],[1,2,3,4],[5,6,7,8]]])
print(d2[:3, 0:3, :2])

[[[11 12]
  [15 16]
  [19 20]]

 [[23 24]
  [27 28]
  [31 32]]

 [[35 36]
  [ 1  2]
  [ 5  6]]]


In [106]:
d4= np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
d4.shape

(3, 4)

In [111]:
d5= np.transpose(d4)
print(d5)

[[11 15 19]
 [12 16 20]
 [13 17 21]
 [14 18 22]]


In [112]:
d5.shape

(4, 3)

In [114]:
y = np.array([1,2,3,4,5,6,7,8,9])
y1 =y.reshape(3,3)
print(y1) # can change dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [116]:
v = np.random.randint(10,55, size = (2,3,4))
print(v)

[[[19 40 26 38]
  [44 47 47 45]
  [43 24 36 33]]

 [[31 54 27 38]
  [52 48 22 39]
  [19 35 30 45]]]


In [122]:
v3 = (2,4,5)
v2 = np.resize(v, v3)
print(v2) # reapets old values if extra row or column is added

[[[19 40 26 38 44]
  [47 47 45 43 24]
  [36 33 31 54 27]
  [38 52 48 22 39]]

 [[19 35 30 45 19]
  [40 26 38 44 47]
  [47 45 43 24 36]
  [33 31 54 27 38]]]


In [123]:
# or method
v2 = np.resize(v, (2,4,5))
print(v2)

[[[19 40 26 38 44]
  [47 47 45 43 24]
  [36 33 31 54 27]
  [38 52 48 22 39]]

 [[19 35 30 45 19]
  [40 26 38 44 47]
  [47 45 43 24 36]
  [33 31 54 27 38]]]


In [133]:
#flatten
w = np.random.randint(10,55, size = (2,3,4))
w3 = w.shape
print(w3)
w2= w.flatten()
print(w2)

(2, 3, 4)
[38 19 24 32 17 48 18 11 39 33 27 21 24 28 51 18 27 40 45 31 53 37 40 10]


In [134]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])
print(x1+x2)

[ 7  9 11 13 15]


In [135]:
print(x1-x2)

[-5 -5 -5 -5 -5]


In [136]:
print(x1*x2)

[ 6 14 24 36 50]


In [137]:
print(x1/x2)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [138]:
z1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(z1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [139]:
print(np.sum(z1))

55


In [140]:
print(np.min(z1))

1


In [142]:
print(np.mean(z1))
print(np.max(z1))

5.5
10


In [143]:
print(np.std(z1)) # std deviation

2.8722813232690143


In [144]:
print(np.sum(z1, axis = 0)) # column wise sum

[ 7  9 11 13 15]


In [145]:
print(np.sum(z1, axis = 1))

[15 40]
