In [4]:
#.Create a 1D NumPy array with numbers from 1 to 10.
import numpy as np
a= np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#2.Create a NumPy array of zeros of size 5.
b = np.zeros(5, dtype = int)
print(b)

[0 0 0 0 0]


In [10]:
#3.Create a NumPy array of ones of size 4 × 4.
c = np.ones((4,4), dtype = int)
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
#4.Create an array of even numbers from 2 to 20.
d= np.arange(2,21,2)
print(d)

[ 2  4  6  8 10 12 14 16 18 20]


In [12]:
#5.Create an array with values from 10 to 50, step 5.
e = np.arange(10,51,5)
print(e)

[10 15 20 25 30 35 40 45 50]


In [13]:
#6.Create an array [1, 2, 3] and multiply it by 3.
f = np.array([1,2,3])
print(f)

[1 2 3]


In [14]:
f*3

array([3, 6, 9])

In [15]:
#7.Create two arrays and add them element-wise.
g = np.array([1,2,3])
print(g)
g2 = np.array([11,12,13])
print(g+g2)

[1 2 3]
[12 14 16]


In [18]:
#8.Create an array [10, 20, 30, 40] and find its mean.
h = np.array([10,20,30,40])
print(np.mean(h))

25.0


In [19]:
#9.Create an array [4, 9, 16, 25] and find the square root.
i = np.array([4,9,16,25])
print(np.sqrt(i))

[2. 3. 4. 5.]


In [23]:
#10.Create a random array of size 5 and find its sum.
j = np.random.randint(1,100,size = 5)
print(np.sum(j))

172


In [25]:
#11.Slice the first 5 elements from an array of numbers from 1 to 10.
k = np.arange(1,11)
print(k[:5])

[1 2 3 4 5]


In [27]:
#12.Get the last two elements of [10, 20, 30, 40, 50].
l = np.arange(10,51,10)
print(l[-2:])

[40 50]


In [28]:
#13.Change the 3rd element of [1, 2, 3, 4, 5] to 99.
m = np.array([1,2,3,4,5])
m[2] =99
print(m)

[ 1  2 99  4  5]


In [33]:
#14.Create a 3×3 matrix and access the element in the 2nd row, 3rd column.
n = np.random.randint(1,10,size = (3,3))
print(n)
print(n[1,2])

[[5 8 3]
 [4 8 3]
 [8 4 6]]
3


In [39]:
#15.Create a 1D array and reverse it using slicing.
o = np.array([1,2,3,4,5,6,7,8])
print(o[::-1])

[8 7 6 5 4 3 2 1]


In [40]:
#16.Generate a random integer between 1 and 100.
p =np.random.randint(1,100)
print(p)

33


In [41]:
#17.Generate a random array of size 3 × 3.
n = np.random.randint(1,10,size = (3,3))
print(n)

[[3 6 6]
 [4 5 3]
 [7 3 8]]


In [44]:
#18.Generate 5 random numbers from a normal distribution.
p = np.random.randn(5)
print(p) 
# Generate 5 random numbers ~ N(0, 1)

[ 0.4467573  -0.63192436 -1.04743782 -0.2625512  -0.01266378]


In [46]:
#19.Generate 10 random numbers between 0 and 1.
q = np.random.random(10)
print(q)

[0.67450302 0.98900934 0.3562936  0.37075152 0.68289214 0.51036633
 0.510116   0.10590127 0.72987827 0.64944795]


In [49]:
#20.Shuffle an array [1, 2, 3, 4, 5] randomly.
r = np.array([1, 2, 3, 4, 5])
np.random.shuffle(r)
print(r)

[1 3 2 4 5]


In [53]:
#21.Transpose a 2×3 matrix.
s= np.random.randint(1,10, size = (2,3))
print(s)

[[3 9 8]
 [2 1 6]]


In [55]:
print(np.transpose(s))

[[3 2]
 [9 1]
 [8 6]]


In [57]:
np.shape(s)

(2, 3)

In [59]:
#22.Reshape a 1D array (1 to 12) into 3×4.
t = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_shape = (3,4)
print(np.reshape(t, new_shape))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [65]:
#23.Resize a 1D array of size 5 into 3×3 (showing how elements repeat or using zero padding).
u = np.array([1,2,3])
new_shape =(3,3)
print(np.resize(u,new_shape))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
#24.Convert a 2D array into 1D.
v = np.array([[1,2,3],[4,5,6]])
print(v)
print(v.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
